### ISSUE TITLE
Improve performance of push phase

### ISSUE THREAD

**Issue by smola** [src-d/borges#115]
go-git:
* [x] Reuse index https://github.com/src-d/go-git/pull/510
* [x] Reuse cache between different packfile decoder instances https://github.com/src-d/go-git/pull/514
* [x] Reuse deltas when creating packfiles https://github.com/src-d/go-git/pull/515
* [x] revlist: ignore all objects reachable from ignored objects https://github.com/src-d/go-git/pull/516

borges:
* [x] update go-git https://github.com/src-d/borges/pull/126

**Comment by ajnavarro** [comment]
https://github.com/src-d/borges/pull/126

this go-git has a lot of new performance improvements. Should close this issue @smola ?
