### ISSUE TITLE
Some repositories exceeded the deadline

### ISSUE THREAD

**Issue by erizocosmico** [src-d/borges#149]
After less than one day running, there are a few repositories that exceeded the deadline (which is 10h), we should investigate the cause of that.

The repositories are the following on the staging cluster:

https://git.openstack.org/openstack/fuel-plugin-contrail
* root=ac5fe3832f3e0544aaaab11685b9bd4c3ff75095
* root=e4e4a9ab3eba7b0ef8ccc2b0dca57ada3313c6e8

https://git.openstack.org/openstack/glance
* root=5b628a687302a6084aed7c293afc8cacfb8b5de9
* root=78b45ee909994eef9fbdeba59bb91d9fc955272b

git://github.com/jakedouglas/rails
* root=db045dbbf60b53dbe013ef25554fd013baf88134

https://git.openstack.org/openstack/deb-nova
* root=a5d70a6d729cc62dec86f371f4b1c00ce13226a4
* root=fd2a015f8b37e6edba8c20d62a67ee68bc48c7e6
* root=bf6e6e718cdc7488e2da87b21e258ccc065fe499

git://github.com/Martin9527/FFmpeg
* root=77bb6835ba752bb9335d208963a53227bbb1bc63

git://github.com/ismaquias/redesComplexas
* root=ad3b6c0dc95b6b05ed294f3d6513e2649a622462

git://github.com/chenzhirong/pentaho-kettle
* root=90bfad2be3b15c9165be0804f96a07956bd495fe
* root=d12411617d3df9341db4e1c0456a470136371efe

git://github.com/annkun/cocos2d-x
* root=50c22d725f7c2273a371b5af06854c177016839d

https://git.openstack.org/openstack/ceilometer
* root=ca8dc0f250726f450de26d7dcdbed1cd3aacaea1

**Comment by erizocosmico** [comment]
There are a lot more right now that we've lowered the timeout to 1h. These and `concurrent map access` panics seem to be the only issues thus far.

I'm investigating locally the reason why they take so long, will report when I have more info.

**Comment by erizocosmico** [comment]
Can be reproduced with this:

```go
package main

import (
	"context"
	"os"
	"time"

	"github.com/sirupsen/logrus"

	"gopkg.in/src-d/go-billy.v3/osfs"
	git "gopkg.in/src-d/go-git.v4"
	"gopkg.in/src-d/go-git.v4/config"
	"gopkg.in/src-d/go-git.v4/storage/filesystem"
)

const (
	FetchRefsSpec = config.RefSpec("refs/*:refs/*")
	FetchHEAD     = config.RefSpec("HEAD:refs/heads/master")
)

func main() {
	fs := osfs.New("./testclone")
	storer, err := filesystem.NewStorage(fs)
	assert(err)

	r, err := git.Init(storer, nil)
	assert(err)

	remote, err := r.CreateRemote(&config.RemoteConfig{
		Name: "origin",
		URLs: []string{"https://git.openstack.org/openstack/glance"},
	})
	if err != nil {
		os.RemoveAll("./testclone")
		assert(err)
	}

	o := &git.FetchOptions{
		RefSpecs: []config.RefSpec{FetchHEAD, FetchRefsSpec},
	}
	start := time.Now()
	err = remote.FetchContext(context.Background(), o)
	assert(err)
	logrus.WithField("elapsed", time.Since(start)).Info("finished cloning")
}

func assert(err error) {
	if err != nil {
		logrus.Fatal(err)
	}
}
```

**Comment by erizocosmico** [comment]
I'll keep here all my findings about the performance issues.

For now there seem to be two fronts:

- Push time 

Still no idea why. Needs intensive profiling but will take some time, as this process is really slow.

- Clone time
 
Analysis done thus far suggests that there are two possible things that cause this: either a lot of objects or a lot of references. Take this with a pinch of salt, though, as they are very preliminary findings.

**Comment by erizocosmico** [comment]
Let's wait til [this](https://github.com/src-d/borges/pull/152) is merged and deployed, which will hopefully solve all these issues.

**Comment by bzz** [comment]
@erizocosmico do you think this is still reproducible with latest borges/go-git ?

**Comment by erizocosmico** [comment]
Hard to tell without processing all repos again, the set we're processing is not representative to know if it's fixed or not. Anyway, it should be much faster and we've actually processed very big repositories. But I can't say for sure. I'd leave it open until we're 100 % certain the problem's gone.

**Comment by jfontan** [comment]
`borges pack` took less than 3 hours to process a list with those repos.

```
18141.06user 454.37system 2:44:06elapsed 188%CPU (0avgtext+0avgdata 39578144maxresident)k
9382360inputs+43170224outputs (20213major+24027016minor)pagefaults 0swaps
```
