### ISSUE TITLE
Out of Memory error processing repo because of lots of roots

### ISSUE THREAD

**Issue by erizocosmico** [src-d/borges#169]
Memory consumption keeps growing and growing until the machine runs out of it and the process crashes.
One notable thing is that this repo has more than 8k roots, so maybe we're not freeing some resources and are stored until the very end of the process. 

Repo in question: https://github.com/android/platform_frameworks_base

**Comment by bzz** [comment]
This could be the case why `borges producer` gets killed every 2h on core OS of science-3 :/
It could not collect more then 5k repos in the row.

**Comment by erizocosmico** [comment]
Not likely, this is a very specific case which happens with a very very strange git usage. You could verify with `git log --max-parents=0` (i think it was that comment) on the offending repositories, but I don't believe it's that case.

**Comment by bzz** [comment]
I see. Just saying that containers get stopped with SIGKILL every 2h, which could be done by OS in case process takes to much memory, as nothing suspicious present in any logs.

**Comment by erizocosmico** [comment]
Yep, but that might be a completely separate issue.

**Comment by jfontan** [comment]
With latest release it took 9 hours and consumed 19GiB of ram at most. These numbers can be improved but I believe the repo can now be processed in a machine with enough RAM.

**Comment by erizocosmico** [comment]
Closing, then
