### ISSUE TITLE
siva index read failed: invalid argument to seek

### ISSUE THREAD

**Issue by erizocosmico** [src-d/borges#170]
Processing this repo (https://github.com/EFForg/https-everywhere) causes the following error:

```
push to rooted repo e3aec08d7b5374acd6f7664cfc9f0f739a5f9dec failed: index read failed: seek /borges/tmp/086757679/transactioner/e3aec08d7b5374acd6f7664cfc9f0f739a5f9dec/1505908434454171283.siva: invalid argument
```

**Comment by ajnavarro** [comment]
@jfontan This could be fixed by https://github.com/src-d/core-retrieval/pull/44 ?

**Comment by jfontan** [comment]
That specific error usually happens when the siva file is corrupted. Can you execute `siva list e3aec08d7b5374acd6f7664cfc9f0f739a5f9dec.siva` and check if it works?

**Comment by jfontan** [comment]
And yes @ajnavarro. If the siva file is corrupted most probably that pull request fixes it.

**Comment by jfontan** [comment]
New siva files shouldn't be broken anymore. There still exist some that are broken and can give that error. The best thing we can do is deleting those siva files and setting their child repositories to error so they can be downloaded again.
