### ISSUE TITLE
Add bucketing on root-repositories folder

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#180]

**Comment by jfontan** [comment]
Downloaded the list of 1048576 siva files to check how many files will go into each bucket.

* 2 characters:
  * max: 4251
  * median: 4100
* 4 characters:
  * max: 36
  * median: 16

HDFS by default allows 1048576 files per directory. Either using 2 or 4 characters per bucket.

**Comment by erizocosmico** [comment]
If both are ok, imho it's better to use 2, less `ls`s in case of a full list :+1:

**Comment by ajnavarro** [comment]
yep, 2 LGTM
