### ISSUE TITLE
Cleanup CONFIG_TEMP_DIR on startup

### ISSUE THREAD

**Issue by rporres** [src-d/borges#191]
To make sure that we don't collect garbage there from multiple runs of the daemon.

We've experimented this on a kubernetes cluster where borges is restarted if it forcibly exits.

**Comment by jfontan** [comment]
This is being addressed in https://github.com/src-d/core-retrieval/pull/45

**Comment by jfontan** [comment]
Fix merged. Will be included in the next release.
