### ISSUE TITLE
Metrics and estimation for version 0.11.x

### ISSUE THREAD

**Issue by mcarmonaa** [src-d/borges#216]
- Information placed in this [spreadsheet](https://drive.google.com/open?id=10AHP6-mzHpBu25hFqX1jgC3LLXrSCf0rOaLUkHZ6Mkg)

- Script to ingest and retrieve the information [here](https://gist.github.com/mcarmonaa/3b5230ad53e76b950752ce035d9643fa)

- Script to process hdfs ls info [here](https://gist.github.com/mcarmonaa/86fde57544ebfa1c250142facc53abca)

**Comment by eiso** [comment]
@mcuadros I saw that @rporres is adding 15 more machines, how many machines does that make in total running borges, and after we have fetched them all, how do we plan to keep the repositories updated (events API of GH?)

I am asking this to understand where we'll be on our Q1 objective related to the Paris pipeline (https://github.com/src-d/guide/tree/master/general/OKRs#engineering).

**Comment by eiso** [comment]
@mcuadros answered my questions [here](https://github.com/src-d/minutes/pull/162)
