### ISSUE TITLE
Manage correctly empty repositories

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#224]
Instead of throw the next error: 
`level=error msg="unable to process repository" err="repository has no HEAD`
we should manage correctly empty repositories.

Some examples:
- https://github.com/OmniSharp/OmniSharp
- https://github.com/fossasia/libregraphics.asia

**Comment by erizocosmico** [comment]
Was this closed by mistake or solved by an issue? If so we should link it here.

**Comment by ajnavarro** [comment]
Yes, I don't know why... fat fingers :P

**Comment by erizocosmico** [comment]
If the repo is empty, rooted transactioner creates an empty one, always with the same hash for all empty repos. This behavior is ok, actually, it was a case that was just not handled in the borges-indexer.
