### ISSUE TITLE
Migration path for upstream references

### ISSUE THREAD

**Issue by erizocosmico** [src-d/borges#234]
We need a migration path to be able to deploy new borges. Until then, all we can do is backport things to 0.11.x, which gets more complicated as time goes by and features are added to both core-retrieval and borges upstream (specially because of the different package managers between master and 0.11.x)

We need to decide on one of the following options: 

- Delete everything and start over with the new schema (which I don't think it's feasible given how slow borges still is)
**Advantage:** we'd get rid of all go-git/siva errors we've had all this time.
**Downside:** we lose months worth of processed repositories.
- Stop all borges instances and have a script that visits each repository and extracts the JSON from it and moves it to its correspondent tables. This has a few caveats, tho. We can't use master core-retrieval to retrieve it because it would have no references field, so no way of getting the JSON with the refs. We need a previous version and a handcrafted SQL query to insert the data without kallax (or have both versions of core-retrieval, one for reading and the other for inserting). This migration could potentially take hours. But I guess a few hours is not much of a stop compared to months of processing being discarded.
**Advantage:** we don't lose anything.
**Downside:** all errors ever happened with siva files are still there.

Until we figure this out there's no way to deploy the new version of borges and any of the improvements it has. We could also stop worrying about 0.11.x branch and stop back-porting things to it.

Thoughts? /cc @ajnavarro @mcarmonaa @jfontan

**Comment by ajnavarro** [comment]
Closing as done
