### ISSUE TITLE
Appending to siva files in HDFS

### ISSUE THREAD

**Issue by mcarmonaa** [src-d/borges#236]
As a first step I forked the current [go-client](https://github.com/colinmarc/hdfs) for HDFS the consumer is using to add functionality to create a file if not exist when an append operation is performed. [here](https://github.com/mcarmonaa/hdfs) the fork, just in case it would be useful at some point.

Apart of that, it raised the question: **will be this feature valuable?**

Append directly to siva files in HDFS could be a great performance increasement but doing that, if an error happens, the siva file would stay in a corrupted status. To avoid it, the same approach is being used right now should be addessed

First, create a copy of the siva file to push changes in HDFS `hdfs://whatever/siva-file.copy`. Then, append to that file the changes and mv to the "real" siva file `hdfs://whatever/siva-file.siva`.

The problem comes from the fact that copying files from HDFS to HDFS, makes HDFS read, copy, replicate and distribute all the file's blocks across the cluster again.

So eventually, the same data is necessary to be moved by HDFS performing appends than with the current approach wich copy all the siva file with the changes to HDFS again.

**Comment by ajnavarro** [comment]
not possible on HDFS
