### ISSUE TITLE
Deploy new borges version on staging cluster

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#239]
- Create new Borges version with latest changes
- Create a new postgres DB on service nodes
- Deploy that new version using the new postgres with the new schema
- Delete all previous data from old postgres deployment

**Comment by erizocosmico** [comment]
Checklist:

- [ ] Stop and remove previous deployments of borges and rovers
- [ ] Remove all data in HDFS
- [ ] Drop database tables for borges
- [ ] Truncate db tables for rovers
- [ ] Create new db schema for borges
- [ ] Clean message queue
  - [ ] Borges
  - [ ] Rovers
- [ ] PR new deployment files
- [ ] Start new deployments
  - [ ] Rovers
  - [ ] Borges

**Comment by ajnavarro** [comment]
@erizocosmico also we should move our postgres instance to a services node.
