### ISSUE TITLE
Producer to requeue elements from buried queue

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#242]
We have two kinds of errors; `fatal` and `non-fatal`

`fatal` errors should go directly to buried queue to analyze them. Fatal errors will be uncaught and caught panics.

`non-fatal` errors can be divided into two subtypes; temporary and permanent errors.

Into permanent errors, we have only two types `ErrRepositoryNotFound` and `ErrAuthNeeded`. The first one is already managed on the database as a specific flag. We need to do the same with the authorization error.

In temporary errors, we have the rest. Temporary errors will have a retries header. If the job is retried the maximum number of times, the job will be sent to the buried queue. Temporary errors will have a special header; `error-type: temporary` to be able to filter and analyze them in a different way than fatal errors.

The producer will get data from the buried queue every 1hr to get temporary errors (that time should be configurable). To do this, you can read the entire queue when the producer is triggered and call to `Reject(true)` to add again to the queue to be processed on the next triggering of the producer.

The producer will be in charge to modify the status flag on the database for the specified job to make able to process it.

**Comment by ajnavarro** [comment]
@mcarmonaa I changed the description of the task, to be more clear.

**Comment by mcarmonaa** [comment]
Great! :+1:

**Comment by ajnavarro** [comment]
@smola @mcuadros here is my proposal for error handling on borges, please have a look.
