### ISSUE TITLE
Improve command organization

### ISSUE THREAD

**Issue by jfontan** [src-d/borges#244]
Right now there are two types of producers (from mentions or from file) and there will be a new one soon (repository updates). Check what could be the best way to organize this. Examples:

* Maintain the current producer and add a new one for updates
* Split producer in mentions, from file commands and updates
* Add a new parameter to producer to start the updater

**Comment by mcarmonaa** [comment]
I'm working on this before address the changes on #250 that require that functionality works as one of this commands.
