### ISSUE TITLE
Standardise logging library in borges (gopkg.in/src-d/go-logger.v1)

### ISSUE THREAD

**Issue by kuba--** [src-d/borges#262]
if something is missed try to enhance gopkg.in/src-d/go-logger.v1 library instead of replace it by any thirdparty (log15, logrus, ...)

**Comment by kuba--** [comment]
Check: https://github.com/src-d/borges/pull/261#issuecomment-383557288

**Comment by jfontan** [comment]
borges is now using go-log library.
