### ISSUE TITLE
Implement graceful shutdown

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#263]
To avoid erroed repositories when, per example, a new borges version is deployed on the server, we should wait for:
- Copy all the siva files that we are copying
- Cancel actual clones
- Cancel getting new repositories from the queue.

Basically, do all we can to avoid erroed repositories for no reason.

**Comment by rporres** [comment]
This is how kubernetes handles pod termination: https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods

TL; DR: `SIGTERM` to the container main process + sleep 30 + `SIGKILL`

**Comment by erizocosmico** [comment]
As @rporres said, we can try to do all that but nothing assures us that 30 seconds is going to be enough to finish all we need to copy and so on. It's more robust than now, yes, but still not bulletproof.

There is a `--grace-period` flag, but I don't know if it's for redeploys as well.

**Comment by rporres** [comment]
I'd say it is safer to cancel current push/copy or whatever Borges is doing and make sure that state is consistent making sure that no half-copied files exist and Rabbit job is going to be handled by some other worker at a later time.

Most likely this should be implemented after the generalisation of the copy-siva-to-tmp mechanism. See https://github.com/src-d/core-retrieval/issues/57

**Comment by erizocosmico** [comment]
Between #265 and https://github.com/src-d/core-retrieval/issues/58 everything about this issue should be covered (once https://github.com/src-d/core-retrieval/issues/58 is integrated in borges).

**Comment by rporres** [comment]
@erizocosmico what happens with a job that is caught in the middle of the shutdown?

**Comment by erizocosmico** [comment]
The copy and the clones are all cancelled
On Tue, 24 Apr 2018 at 19:05, Rafael Porres Molina <notifications@github.com<mailto:notifications@github.com>> wrote:

@erizocosmico<https://github.com/erizocosmico> what happens with a job that is caught in the middle of the shutdown?

**Comment by rporres** [comment]
I mean if it's requeued 😌

**Comment by rporres** [comment]
I mean if it's requeued 😌There's some logic to requeue failed jobs [in the PR](https://github.com/erizocosmico/borges/blob/45902e13ce7cab9e8037aa4e9ec855ba15721f7d/worker.go#L64-L78) but code is a bit hardcore for me to fully understand everything. I don't know if a cancellation triggers that code path. It looks it doesn't, but my knowledge of go channels is limited and my knowledge of Borges codebase even more limited :joy: Maybe it is not necessary if the job hasn't been removed from the queue yet...

**Comment by erizocosmico** [comment]
Since there is an error, the job is requeued, yes.

**Comment by rporres** [comment]
Hmmm, I think that a shutdown from an operator should not be an error. It can be something as common as a version upgrade that needs a new binary running in a new container...

**Comment by jfontan** [comment]
Is there something we still have to change to have a proper shutdown? Do we want to continue here or can we open a new issue with the specific concern?

**Comment by rporres** [comment]
I guess we can close it and deal with anything we may find with the current implementation in a new issue

**Comment by ajnavarro** [comment]
@jfontan shall we close it?

**Comment by jfontan** [comment]
Yes, we close it and wait for any new issues as @rporres says.
