### ISSUE TITLE
borges producer fails to start

### ISSUE THREAD

**Issue by rporres** [src-d/borges#280]
I'm deploying borges v0.15.0 in k8s using [the official helm chart](https://github.com/src-d/charts/tree/master/borges) using

```
helm install -n borges . --set \
consumer.replicaCount=10,\
nodeSelector."srcd\.host/type"=worker,\
image.tag=v0.15.0,\
consumer.workers=32,\
consumer.loglevel=debug,\
glusterfs.endpoint=glusterfs-cluster,\
glusterfs.volume=git-volume
```

Producer pod is crashing with the message

```
Exception (406) Reason: "PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'rovers' in vhost '/': received the value '8' of type 'byte' but current is none"
```

**Comment by jfontan** [comment]
There is an incompatibility between queues created by rovers versions < 2.6.2. I've updated the readme to note this in #283.

I'm not sure we want to do anything else.

**Comment by rporres** [comment]
nope, closing it
