### ISSUE TITLE
Use sane defaults on Docker

### ISSUE THREAD

**Issue by smola** [src-d/borges#320]
From @dennwc ([more](https://gist.github.com/dennwc/fc869156bc622c788fbc4bd39baf99dc)):

> Too many envs. Should use sane defaults instead. CONFIG_ROOT_REPOSITORIES_DIR, CONFIG_DBHOST, LOG_LEVEL are unnecessary.

Similar issue on rovers: https://github.com/src-d/rovers/issues/192

If defaults are good enough, docker container would be able to run with minimal setup (e.g. just some container links to postgres and rabbit).

**Comment by erizocosmico** [comment]
AFAIK almost all parameters already have defaults. Just adding good defaults to hosts in broker and postgres should be enough
