### ISSUE TITLE
latest docker image does not point to latest release

### ISSUE THREAD

**Issue by smola** [src-d/borges#321]
From @dennwc ([more](https://gist.github.com/dennwc/fc869156bc622c788fbc4bd39baf99dc)):

> Executing the borges_consumer part gave an error: /bin/sh: borges: not found. Used Docker knowledge to check the Quay repo and see that latest tag is pointing to the wrong version (something between 0.11 and 0.12 - it has an unique hash for some reason, which shouldn't be the case). Changed the version to the 0.16.2 manually and it worked.

**Comment by jfontan** [comment]
Fixed in #333
