### ISSUE TITLE
Borges producer hangs if it cannot acquire a lock

### ISSUE THREAD

**Issue by rporres** [src-d/borges#344]
In a k8s deployment, I specified wrongly the locking connection string and borges didn't say anything about it in the logs, it just stayed in that way without giving any further message.

**Comment by rporres** [comment]
I specified a non existing dns entry. Instead of
```
etcd:http://etcd.default.svc.cluster.local:2379
```
I used
```
etcd:http://etcd.borges.svc.cluster.local:2379
```
note the change in the namespace in the etcd fqdn

**Comment by kuba--** [comment]
@rporres it happened because you didn't specify `?dial-timeout=...` parameter. 
I'll fix it by setting default value.
@jfontan - 3s. sounds good to you as a default `dial-timeout` for `etcd`?

**Comment by jfontan** [comment]
I suppose that 3 seconds should be enough. What's the default timeout?

**Comment by kuba--** [comment]
This is the problem - there is no default, we have to pick up sth.
But `healthBalancer` uses this one: `minHealthRetryDuration = 3 * time.Second`, so I suppose it's ok to use the same value.

**Comment by jfontan** [comment]
I would use that then. It can be specified in the etcd url I believe:

```
etcd:http://etcd:2379?dial-tiemout=3s
```
