### ISSUE TITLE
Histogram of number number of repos per siva file

### ISSUE THREAD

**Issue by jfontan** [src-d/borges#390]
From the database get statistics of the number of repos per siva file. For example:

| repos | number of sivas |
|--|--|
| 1  | 5000 |
| 2 | 4500 |
| 3 | 4000 |

**Comment by mcarmonaa** [comment]
Data collected with the query:

```sql
SELECT
    t.repos AS n_repos, count(t.init) AS n_sivas
FROM (
    SELECT
        count(distinct(repository_id)) AS repos,init
    FROM
        repository_references
    GROUP BY
        init
    ) AS t
GROUP BY
    t.repos
ORDER BY
    n_repos ASC
```

Histrogram: n_sivas values are in logarithmic scale (y-axis), the graphic only contains de 150 firsts values.

![histogram-logarithmic](https://user-images.githubusercontent.com/16907441/54761527-2bc0d900-4bea-11e9-8341-93bda7eb0564.png)

DATA:

Total siva files when the query was executed: 21_377_103

| n_repos | n_sivas  | 
|---------|----------| 
| 1       | 19424412 | 
| 2       | 1223410  | 
| 3       | 297895   | 
| 4       | 126706   | 
| 5       | 68312    | 
| 6       | 42888    | 
| 7       | 29138    | 
| 8       | 21558    | 
| 9       | 15996    | 
| 10      | 13415    | 
| 11      | 10704    | 
| 12      | 9093     | 
| 13      | 7775     | 
| 14      | 6649     | 
| 15      | 5637     | 
| 16      | 4803     | 
| 17      | 4304     | 
| 18      | 3750     | 
| 19      | 3368     | 
| 20      | 3099     | 
| 21      | 2701     | 
| 22      | 2517     | 
| 23      | 2387     | 
| 24      | 2090     | 
| 25      | 1892     | 
| 26      | 1779     | 
| 27      | 1699     | 
| 28      | 1606     | 
| 29      | 1411     | 
| 30      | 1294     | 
| 31      | 1218     | 
| 32      | 1145     | 
| 33      | 1058     | 
| 34      | 993      | 
| 35      | 972      | 
| 36      | 805      | 
| 37      | 984      | 
| 38      | 852      | 
| 39      | 748      | 
| 40      | 778      | 
| 41      | 690      | 
| 42      | 710      | 
| 43      | 774      | 
| 44      | 583      | 
| 45      | 545      | 
| 46      | 581      | 
| 47      | 616      | 
| 48      | 567      | 
| 49      | 469      | 
| 50      | 451      | 
| 51      | 460      | 
| 52      | 397      | 
| 53      | 369      | 
| 54      | 414      | 
| 55      | 392      | 
| 56      | 353      | 
| 57      | 360      | 
| 58      | 347      | 
| 59      | 331      | 
| 60      | 333      | 
| 61      | 299      | 
| 62      | 313      | 
| 63      | 314      | 
| 64      | 294      | 
| 65      | 255      | 
| 66      | 248      | 
| 67      | 250      | 
| 68      | 222      | 
| 69      | 227      | 
| 70      | 254      | 
| 71      | 211      | 
| 72      | 190      | 
| 73      | 211      | 
| 74      | 191      | 
| 75      | 183      | 
| 76      | 184      | 
| 77      | 150      | 
| 78      | 164      | 
| 79      | 159      | 
| 80      | 162      | 
| 81      | 168      | 
| 82      | 143      | 
| 83      | 139      | 
| 84      | 138      | 
| 85      | 156      | 
| 86      | 170      | 
| 87      | 151      | 
| 88      | 128      | 
| 89      | 116      | 
| 90      | 102      | 
| 91      | 121      | 
| 92      | 131      | 
| 93      | 114      | 
| 94      | 110      | 
| 95      | 119      | 
| 96      | 93       | 
| 97      | 101      | 
| 98      | 107      | 
| 99      | 102      | 
| 100     | 114      | 
| 101     | 117      | 
| 102     | 96       | 
| 103     | 97       | 
| 104     | 123      | 
| 105     | 82       | 
| 106     | 76       | 
| 107     | 78       | 
| 108     | 96       | 
| 109     | 93       | 
| 110     | 87       | 
| 111     | 72       | 
| 112     | 73       | 
| 113     | 82       | 
| 114     | 71       | 
| 115     | 82       | 
| 116     | 83       | 
| 117     | 79       | 
| 118     | 69       | 
| 119     | 50       | 
| 120     | 72       | 
| 121     | 75       | 
| 122     | 66       | 
| 123     | 72       | 
| 124     | 63       | 
| 125     | 63       | 
| 126     | 75       | 
| 127     | 61       | 
| 128     | 62       | 
| 129     | 56       | 
| 130     | 74       | 
| 131     | 68       | 
| 132     | 64       | 
| 133     | 49       | 
| 134     | 45       | 
| 135     | 83       | 
| 136     | 69       | 
| 137     | 55       | 
| 138     | 51       | 
| 139     | 50       | 
| 140     | 51       | 
| 141     | 41       | 
| 142     | 46       | 
| 143     | 49       | 
| 144     | 51       | 
| 145     | 47       | 
| 146     | 47       | 
| 147     | 40       | 
| 148     | 38       | 
| 149     | 42       | 
| 150     | 39       | 
| 151     | 44       | 
| 152     | 39       | 
| 153     | 36       | 
| 154     | 35       | 
| 155     | 41       | 
| 156     | 26       | 
| 157     | 49       | 
| 158     | 36       | 
| 159     | 26       | 
| 160     | 53       | 
| 161     | 34       | 
| 162     | 41       | 
| 163     | 44       | 
| 164     | 35       | 
| 165     | 50       | 
| 166     | 38       | 
| 167     | 31       | 
| 168     | 27       | 
| 169     | 23       | 
| 170     | 35       | 
| 171     | 34       | 
| 172     | 24       | 
| 173     | 33       | 
| 174     | 26       | 
| 175     | 34       | 
| 176     | 26       | 
| 177     | 30       | 
| 178     | 30       | 
| 179     | 30       | 
| 180     | 27       | 
| 181     | 25       | 
| 182     | 27       | 
| 183     | 22       | 
| 184     | 31       | 
| 185     | 21       | 
| 186     | 22       | 
| 187     | 27       | 
| 188     | 23       | 
| 189     | 29       | 
| 190     | 30       | 
| 191     | 22       | 
| 192     | 26       | 
| 193     | 19       | 
| 194     | 29       | 
| 195     | 24       | 
| 196     | 26       | 
| 197     | 27       | 
| 198     | 16       | 
| 199     | 27       | 
| 200     | 27       | 
| 201     | 38       | 
| 202     | 13       | 
| 203     | 21       | 
| 204     | 21       | 
| 205     | 17       | 
| 206     | 16       | 
| 207     | 20       | 
| 208     | 24       | 
| 209     | 14       | 
| 210     | 21       | 
| 211     | 17       | 
| 212     | 24       | 
| 213     | 20       | 
| 214     | 23       | 
| 215     | 24       | 
| 216     | 21       | 
| 217     | 24       | 
| 218     | 27       | 
| 219     | 11       | 
| 220     | 14       | 
| 221     | 25       | 
| 222     | 25       | 
| 223     | 22       | 
| 224     | 24       | 
| 225     | 19       | 
| 226     | 22       | 
| 227     | 15       | 
| 228     | 15       | 
| 229     | 13       | 
| 230     | 18       | 
| 231     | 18       | 
| 232     | 4        | 
| 233     | 19       | 
| 234     | 12       | 
| 235     | 16       | 
| 236     | 13       | 
| 237     | 15       | 
| 238     | 14       | 
| 239     | 18       | 
| 240     | 13       | 
| 241     | 9        | 
| 242     | 23       | 
| 243     | 13       | 
| 244     | 16       | 
| 245     | 11       | 
| 246     | 13       | 
| 247     | 10       | 
| 248     | 15       | 
| 249     | 14       | 
| 250     | 11       | 
| 251     | 22       | 
| 252     | 12       | 
| 253     | 17       | 
| 254     | 12       | 
| 255     | 13       | 
| 256     | 15       | 
| 257     | 17       | 
| 258     | 14       | 
| 259     | 14       | 
| 260     | 21       | 
| 261     | 16       | 
| 262     | 15       | 
| 263     | 18       | 
| 264     | 13       | 
| 265     | 21       | 
| 266     | 9        | 
| 267     | 11       | 
| 268     | 16       | 
| 269     | 20       | 
| 270     | 7        | 
| 271     | 7        | 
| 272     | 13       | 
| 273     | 8        | 
| 274     | 11       | 
| 275     | 8        | 
| 276     | 16       | 
| 277     | 14       | 
| 278     | 12       | 
| 279     | 6        | 
| 280     | 10       | 
| 281     | 12       | 
| 282     | 4        | 
| 283     | 11       | 
| 284     | 12       | 
| 285     | 16       | 
| 286     | 11       | 
| 287     | 5        | 
| 288     | 10       | 
| 289     | 10       | 
| 290     | 4        | 
| 291     | 8        | 
| 292     | 9        | 
| 293     | 5        | 
| 294     | 13       | 
| 295     | 13       | 
| 296     | 4        | 
| 297     | 6        | 
| 298     | 9        | 
| 299     | 13       | 
| 300     | 5        | 
| 301     | 9        | 
| 302     | 6        | 
| 303     | 13       | 
| 304     | 13       | 
| 305     | 19       | 
| 306     | 11       | 
| 307     | 8        | 
| 308     | 11       | 
| 309     | 7        | 
| 310     | 6        | 
| 311     | 6        | 
| 312     | 9        | 
| 313     | 7        | 
| 314     | 4        | 
| 315     | 14       | 
| 316     | 4        | 
| 317     | 6        | 
| 318     | 6        | 
| 319     | 1        | 
| 320     | 4        | 
| 321     | 6        | 
| 322     | 9        | 
| 323     | 9        | 
| 324     | 6        | 
| 325     | 6        | 
| 326     | 10       | 
| 327     | 4        | 
| 328     | 9        | 
| 329     | 4        | 
| 330     | 9        | 
| 331     | 8        | 
| 332     | 4        | 
| 333     | 7        | 
| 334     | 6        | 
| 335     | 5        | 
| 336     | 3        | 
| 337     | 6        | 
| 338     | 9        | 
| 339     | 5        | 
| 340     | 8        | 
| 341     | 8        | 
| 342     | 8        | 
| 343     | 11       | 
| 344     | 11       | 
| 345     | 9        | 
| 346     | 4        | 
| 347     | 9        | 
| 348     | 10       | 
| 349     | 8        | 
| 350     | 2        | 
| 351     | 6        | 
| 352     | 3        | 
| 353     | 2        | 
| 354     | 8        | 
| 355     | 8        | 
| 356     | 11       | 
| 357     | 6        | 
| 358     | 8        | 
| 359     | 5        | 
| 360     | 9        | 
| 361     | 1        | 
| 362     | 7        | 
| 363     | 11       | 
| 364     | 3        | 
| 365     | 7        | 
| 366     | 7        | 
| 367     | 5        | 
| 368     | 5        | 
| 369     | 7        | 
| 370     | 6        | 
| 371     | 9        | 
| 372     | 6        | 
| 373     | 7        | 
| 374     | 11       | 
| 375     | 5        | 
| 376     | 8        | 
| 377     | 12       | 
| 378     | 7        | 
| 379     | 9        | 
| 380     | 3        | 
| 381     | 8        | 
| 382     | 4        | 
| 383     | 9        | 
| 384     | 5        | 
| 385     | 5        | 
| 386     | 10       | 
| 387     | 8        | 
| 388     | 3        | 
| 389     | 5        | 
| 390     | 9        | 
| 391     | 6        | 
| 392     | 5        | 
| 393     | 7        | 
| 394     | 2        | 
| 395     | 1        | 
| 396     | 6        | 
| 397     | 5        | 
| 398     | 6        | 
| 399     | 8        | 
| 400     | 5        | 
| 401     | 5        | 
| 402     | 8        | 
| 403     | 5        | 
| 404     | 4        | 
| 405     | 1        | 
| 406     | 4        | 
| 407     | 3        | 
| 408     | 3        | 
| 409     | 5        | 
| 410     | 4        | 
| 411     | 3        | 
| 412     | 3        | 
| 413     | 3        | 
| 414     | 8        | 
| 415     | 4        | 
| 416     | 2        | 
| 417     | 7        | 
| 418     | 4        | 
| 419     | 5        | 
| 420     | 6        | 
| 421     | 2        | 
| 422     | 2        | 
| 423     | 5        | 
| 424     | 2        | 
| 425     | 5        | 
| 426     | 8        | 
| 427     | 1        | 
| 428     | 8        | 
| 429     | 8        | 
| 430     | 1        | 
| 431     | 5        | 
| 432     | 7        | 
| 433     | 5        | 
| 434     | 7        | 
| 435     | 5        | 
| 436     | 1        | 
| 437     | 2        | 
| 438     | 3        | 
| 439     | 2        | 
| 440     | 7        | 
| 441     | 2        | 
| 442     | 2        | 
| 443     | 5        | 
| 444     | 2        | 
| 445     | 5        | 
| 446     | 2        | 
| 448     | 5        | 
| 449     | 5        | 
| 450     | 2        | 
| 451     | 8        | 
| 452     | 4        | 
| 453     | 6        | 
| 454     | 3        | 
| 455     | 5        | 
| 456     | 6        | 
| 457     | 2        | 
| 458     | 7        | 
| 459     | 2        | 
| 460     | 5        | 
| 461     | 5        | 
| 462     | 4        | 
| 463     | 6        | 
| 464     | 4        | 
| 465     | 6        | 
| 466     | 5        | 
| 467     | 5        | 
| 468     | 6        | 
| 469     | 2        | 
| 470     | 5        | 
| 471     | 4        | 
| 472     | 3        | 
| 473     | 2        | 
| 474     | 1        | 
| 475     | 1        | 
| 476     | 3        | 
| 477     | 3        | 
| 478     | 2        | 
| 479     | 5        | 
| 480     | 4        | 
| 481     | 3        | 
| 482     | 4        | 
| 483     | 3        | 
| 484     | 3        | 
| 485     | 2        | 
| 486     | 4        | 
| 487     | 4        | 
| 488     | 2        | 
| 489     | 2        | 
| 490     | 3        | 
| 491     | 1        | 
| 492     | 4        | 
| 493     | 2        | 
| 494     | 3        | 
| 495     | 2        | 
| 496     | 3        | 
| 498     | 2        | 
| 500     | 4        | 
| 501     | 2        | 
| 502     | 1        | 
| 503     | 4        | 
| 504     | 1        | 
| 505     | 4        | 
| 506     | 2        | 
| 507     | 7        | 
| 508     | 3        | 
| 509     | 2        | 
| 510     | 3        | 
| 511     | 6        | 
| 512     | 3        | 
| 513     | 6        | 
| 514     | 2        | 
| 515     | 3        | 
| 516     | 3        | 
| 517     | 3        | 
| 519     | 4        | 
| 520     | 2        | 
| 521     | 1        | 
| 522     | 4        | 
| 523     | 4        | 
| 524     | 3        | 
| 525     | 4        | 
| 526     | 1        | 
| 527     | 7        | 
| 528     | 1        | 
| 529     | 2        | 
| 530     | 3        | 
| 531     | 1        | 
| 532     | 4        | 
| 533     | 1        | 
| 535     | 3        | 
| 536     | 3        | 
| 537     | 2        | 
| 538     | 3        | 
| 539     | 3        | 
| 540     | 1        | 
| 541     | 6        | 
| 542     | 2        | 
| 543     | 3        | 
| 544     | 8        | 
| 545     | 3        | 
| 546     | 3        | 
| 547     | 8        | 
| 548     | 2        | 
| 549     | 7        | 
| 550     | 2        | 
| 551     | 2        | 
| 552     | 1        | 
| 553     | 2        | 
| 554     | 1        | 
| 555     | 1        | 
| 557     | 2        | 
| 558     | 1        | 
| 559     | 2        | 
| 560     | 2        | 
| 561     | 6        | 
| 562     | 5        | 
| 563     | 1        | 
| 565     | 1        | 
| 566     | 1        | 
| 567     | 2        | 
| 568     | 2        | 
| 569     | 3        | 
| 570     | 5        | 
| 571     | 4        | 
| 573     | 2        | 
| 574     | 4        | 
| 575     | 4        | 
| 576     | 1        | 
| 577     | 4        | 
| 578     | 3        | 
| 579     | 2        | 
| 580     | 4        | 
| 581     | 3        | 
| 582     | 1        | 
| 583     | 2        | 
| 584     | 4        | 
| 585     | 4        | 
| 589     | 1        | 
| 590     | 1        | 
| 592     | 2        | 
| 595     | 3        | 
| 596     | 2        | 
| 598     | 5        | 
| 599     | 3        | 
| 601     | 1        | 
| 602     | 1        | 
| 603     | 4        | 
| 604     | 2        | 
| 605     | 2        | 
| 607     | 2        | 
| 608     | 2        | 
| 609     | 5        | 
| 611     | 4        | 
| 612     | 2        | 
| 613     | 4        | 
| 614     | 3        | 
| 616     | 1        | 
| 617     | 4        | 
| 618     | 1        | 
| 619     | 4        | 
| 620     | 1        | 
| 621     | 2        | 
| 622     | 4        | 
| 623     | 3        | 
| 625     | 4        | 
| 627     | 3        | 
| 628     | 3        | 
| 632     | 4        | 
| 636     | 1        | 
| 637     | 3        | 
| 638     | 5        | 
| 639     | 2        | 
| 640     | 1        | 
| 641     | 1        | 
| 642     | 3        | 
| 644     | 2        | 
| 645     | 6        | 
| 647     | 1        | 
| 648     | 3        | 
| 649     | 1        | 
| 650     | 1        | 
| 651     | 3        | 
| 652     | 3        | 
| 653     | 3        | 
| 654     | 2        | 
| 656     | 1        | 
| 657     | 3        | 
| 658     | 1        | 
| 660     | 1        | 
| 661     | 6        | 
| 662     | 2        | 
| 664     | 2        | 
| 665     | 1        | 
| 666     | 2        | 
| 669     | 3        | 
| 670     | 2        | 
| 671     | 1        | 
| 673     | 1        | 
| 674     | 2        | 
| 675     | 3        | 
| 676     | 3        | 
| 678     | 3        | 
| 680     | 2        | 
| 682     | 1        | 
| 683     | 1        | 
| 684     | 3        | 
| 685     | 7        | 
| 686     | 3        | 
| 687     | 1        | 
| 689     | 1        | 
| 690     | 1        | 
| 691     | 1        | 
| 692     | 2        | 
| 693     | 5        | 
| 695     | 6        | 
| 696     | 4        | 
| 697     | 4        | 
| 698     | 1        | 
| 699     | 3        | 
| 700     | 3        | 
| 701     | 1        | 
| 702     | 2        | 
| 703     | 3        | 
| 706     | 3        | 
| 707     | 1        | 
| 709     | 1        | 
| 710     | 1        | 
| 711     | 1        | 
| 713     | 1        | 
| 714     | 2        | 
| 715     | 5        | 
| 716     | 1        | 
| 717     | 1        | 
| 719     | 1        | 
| 720     | 1        | 
| 721     | 6        | 
| 723     | 3        | 
| 725     | 2        | 
| 726     | 2        | 
| 729     | 2        | 
| 732     | 2        | 
| 735     | 2        | 
| 736     | 1        | 
| 737     | 1        | 
| 738     | 1        | 
| 744     | 1        | 
| 745     | 1        | 
| 746     | 1        | 
| 747     | 1        | 
| 748     | 2        | 
| 749     | 2        | 
| 750     | 2        | 
| 751     | 6        | 
| 753     | 1        | 
| 754     | 1        | 
| 755     | 2        | 
| 756     | 4        | 
| 757     | 3        | 
| 758     | 1        | 
| 759     | 1        | 
| 760     | 2        | 
| 761     | 1        | 
| 762     | 5        | 
| 763     | 3        | 
| 765     | 1        | 
| 766     | 1        | 
| 768     | 1        | 
| 769     | 1        | 
| 770     | 1        | 
| 773     | 1        | 
| 774     | 3        | 
| 779     | 1        | 
| 785     | 2        | 
| 786     | 2        | 
| 788     | 2        | 
| 789     | 1        | 
| 790     | 1        | 
| 791     | 3        | 
| 792     | 3        | 
| 795     | 6        | 
| 796     | 4        | 
| 797     | 1        | 
| 798     | 1        | 
| 800     | 3        | 
| 801     | 2        | 
| 805     | 1        | 
| 807     | 1        | 
| 810     | 1        | 
| 812     | 1        | 
| 814     | 1        | 
| 815     | 1        | 
| 816     | 1        | 
| 818     | 2        | 
| 821     | 1        | 
| 822     | 3        | 
| 824     | 3        | 
| 825     | 1        | 
| 827     | 1        | 
| 828     | 1        | 
| 829     | 1        | 
| 830     | 1        | 
| 831     | 1        | 
| 832     | 1        | 
| 837     | 1        | 
| 838     | 4        | 
| 839     | 1        | 
| 845     | 1        | 
| 846     | 1        | 
| 847     | 3        | 
| 848     | 1        | 
| 850     | 1        | 
| 851     | 1        | 
| 852     | 2        | 
| 856     | 3        | 
| 859     | 2        | 
| 861     | 1        | 
| 862     | 2        | 
| 863     | 1        | 
| 868     | 3        | 
| 870     | 2        | 
| 872     | 2        | 
| 873     | 1        | 
| 874     | 1        | 
| 875     | 1        | 
| 879     | 1        | 
| 883     | 2        | 
| 884     | 1        | 
| 885     | 2        | 
| 886     | 1        | 
| 888     | 3        | 
| 890     | 1        | 
| 895     | 1        | 
| 896     | 1        | 
| 897     | 1        | 
| 899     | 1        | 
| 900     | 1        | 
| 901     | 1        | 
| 905     | 2        | 
| 906     | 1        | 
| 908     | 1        | 
| 909     | 1        | 
| 910     | 1        | 
| 911     | 1        | 
| 912     | 1        | 
| 918     | 1        | 
| 920     | 1        | 
| 923     | 1        | 
| 924     | 1        | 
| 925     | 1        | 
| 926     | 1        | 
| 929     | 1        | 
| 931     | 2        | 
| 932     | 1        | 
| 933     | 2        | 
| 936     | 1        | 
| 937     | 1        | 
| 939     | 2        | 
| 940     | 2        | 
| 941     | 1        | 
| 943     | 2        | 
| 945     | 1        | 
| 946     | 1        | 
| 947     | 1        | 
| 948     | 2        | 
| 949     | 3        | 
| 950     | 1        | 
| 952     | 1        | 
| 958     | 1        | 
| 961     | 1        | 
| 962     | 1        | 
| 965     | 2        | 
| 966     | 1        | 
| 967     | 1        | 
| 970     | 2        | 
| 975     | 1        | 
| 978     | 2        | 
| 980     | 1        | 
| 981     | 1        | 
| 982     | 1        | 
| 987     | 1        | 
| 990     | 1        | 
| 991     | 1        | 
| 992     | 1        | 
| 993     | 2        | 
| 994     | 1        | 
| 995     | 1        | 
| 996     | 1        | 
| 998     | 1        | 
| 1001    | 1        | 
| 1003    | 1        | 
| 1009    | 1        | 
| 1012    | 1        | 
| 1013    | 1        | 
| 1015    | 1        | 
| 1017    | 2        | 
| 1020    | 1        | 
| 1023    | 1        | 
| 1024    | 2        | 
| 1025    | 1        | 
| 1028    | 1        | 
| 1029    | 1        | 
| 1030    | 2        | 
| 1032    | 1        | 
| 1033    | 2        | 
| 1034    | 1        | 
| 1036    | 1        | 
| 1037    | 1        | 
| 1040    | 1        | 
| 1042    | 1        | 
| 1043    | 1        | 
| 1045    | 1        | 
| 1047    | 1        | 
| 1048    | 1        | 
| 1049    | 2        | 
| 1053    | 1        | 
| 1056    | 1        | 
| 1057    | 5        | 
| 1061    | 2        | 
| 1066    | 2        | 
| 1067    | 1        | 
| 1068    | 1        | 
| 1069    | 1        | 
| 1071    | 1        | 
| 1072    | 1        | 
| 1075    | 2        | 
| 1078    | 1        | 
| 1079    | 1        | 
| 1084    | 2        | 
| 1085    | 1        | 
| 1090    | 1        | 
| 1093    | 1        | 
| 1094    | 1        | 
| 1096    | 1        | 
| 1097    | 1        | 
| 1102    | 1        | 
| 1107    | 1        | 
| 1108    | 1        | 
| 1109    | 2        | 
| 1121    | 1        | 
| 1122    | 1        | 
| 1126    | 1        | 
| 1128    | 1        | 
| 1130    | 1        | 
| 1131    | 1        | 
| 1132    | 3        | 
| 1134    | 1        | 
| 1136    | 1        | 
| 1143    | 1        | 
| 1144    | 2        | 
| 1145    | 1        | 
| 1146    | 1        | 
| 1149    | 2        | 
| 1153    | 1        | 
| 1154    | 1        | 
| 1155    | 1        | 
| 1160    | 1        | 
| 1162    | 1        | 
| 1166    | 1        | 
| 1168    | 1        | 
| 1172    | 1        | 
| 1175    | 1        | 
| 1178    | 2        | 
| 1179    | 7        | 
| 1180    | 3        | 
| 1181    | 3        | 
| 1187    | 1        | 
| 1188    | 1        | 
| 1190    | 1        | 
| 1193    | 2        | 
| 1197    | 2        | 
| 1201    | 1        | 
| 1203    | 2        | 
| 1208    | 1        | 
| 1209    | 1        | 
| 1213    | 1        | 
| 1223    | 1        | 
| 1224    | 1        | 
| 1226    | 1        | 
| 1227    | 1        | 
| 1228    | 3        | 
| 1229    | 1        | 
| 1230    | 1        | 
| 1231    | 2        | 
| 1238    | 1        | 
| 1243    | 1        | 
| 1248    | 1        | 
| 1250    | 1        | 
| 1253    | 1        | 
| 1255    | 1        | 
| 1266    | 1        | 
| 1268    | 1        | 
| 1272    | 1        | 
| 1274    | 2        | 
| 1275    | 1        | 
| 1290    | 1        | 
| 1293    | 2        | 
| 1296    | 1        | 
| 1304    | 1        | 
| 1312    | 1        | 
| 1314    | 1        | 
| 1316    | 1        | 
| 1318    | 1        | 
| 1320    | 1        | 
| 1323    | 1        | 
| 1340    | 1        | 
| 1350    | 1        | 
| 1358    | 1        | 
| 1361    | 1        | 
| 1362    | 1        | 
| 1383    | 1        | 
| 1387    | 1        | 
| 1391    | 2        | 
| 1395    | 1        | 
| 1402    | 2        | 
| 1406    | 1        | 
| 1411    | 1        | 
| 1413    | 1        | 
| 1426    | 1        | 
| 1428    | 1        | 
| 1430    | 1        | 
| 1432    | 1        | 
| 1439    | 1        | 
| 1441    | 2        | 
| 1452    | 1        | 
| 1453    | 1        | 
| 1465    | 1        | 
| 1468    | 1        | 
| 1472    | 1        | 
| 1474    | 1        | 
| 1475    | 1        | 
| 1482    | 1        | 
| 1487    | 1        | 
| 1495    | 2        | 
| 1499    | 1        | 
| 1503    | 1        | 
| 1506    | 1        | 
| 1507    | 1        | 
| 1509    | 1        | 
| 1525    | 1        | 
| 1531    | 1        | 
| 1532    | 1        | 
| 1533    | 1        | 
| 1537    | 1        | 
| 1545    | 1        | 
| 1551    | 1        | 
| 1564    | 1        | 
| 1569    | 1        | 
| 1578    | 1        | 
| 1579    | 1        | 
| 1580    | 1        | 
| 1587    | 1        | 
| 1615    | 1        | 
| 1619    | 1        | 
| 1636    | 1        | 
| 1645    | 1        | 
| 1656    | 2        | 
| 1661    | 1        | 
| 1662    | 1        | 
| 1666    | 2        | 
| 1671    | 1        | 
| 1674    | 1        | 
| 1676    | 1        | 
| 1694    | 1        | 
| 1698    | 2        | 
| 1699    | 2        | 
| 1710    | 1        | 
| 1723    | 1        | 
| 1753    | 1        | 
| 1757    | 1        | 
| 1759    | 1        | 
| 1760    | 1        | 
| 1763    | 1        | 
| 1765    | 1        | 
| 1776    | 1        | 
| 1780    | 1        | 
| 1784    | 1        | 
| 1786    | 1        | 
| 1821    | 1        | 
| 1836    | 1        | 
| 1854    | 1        | 
| 1886    | 1        | 
| 1887    | 1        | 
| 1899    | 1        | 
| 1904    | 1        | 
| 1946    | 1        | 
| 1955    | 1        | 
| 1961    | 1        | 
| 1967    | 1        | 
| 1970    | 1        | 
| 1974    | 1        | 
| 1990    | 1        | 
| 2003    | 1        | 
| 2005    | 1        | 
| 2009    | 1        | 
| 2013    | 1        | 
| 2015    | 1        | 
| 2019    | 1        | 
| 2030    | 1        | 
| 2039    | 1        | 
| 2054    | 1        | 
| 2059    | 2        | 
| 2096    | 1        | 
| 2097    | 1        | 
| 2100    | 1        | 
| 2102    | 1        | 
| 2140    | 1        | 
| 2146    | 1        | 
| 2147    | 1        | 
| 2151    | 1        | 
| 2167    | 1        | 
| 2186    | 2        | 
| 2212    | 1        | 
| 2221    | 1        | 
| 2249    | 1        | 
| 2260    | 1        | 
| 2264    | 1        | 
| 2273    | 1        | 
| 2277    | 1        | 
| 2304    | 1        | 
| 2352    | 1        | 
| 2376    | 1        | 
| 2377    | 1        | 
| 2410    | 2        | 
| 2444    | 1        | 
| 2449    | 1        | 
| 2523    | 1        | 
| 2525    | 1        | 
| 2532    | 1        | 
| 2557    | 1        | 
| 2657    | 1        | 
| 2659    | 1        | 
| 2703    | 1        | 
| 2706    | 1        | 
| 2731    | 1        | 
| 2734    | 1        | 
| 2811    | 1        | 
| 2895    | 1        | 
| 2924    | 1        | 
| 2926    | 1        | 
| 2927    | 1        | 
| 2929    | 2        | 
| 2931    | 1        | 
| 2932    | 3        | 
| 2933    | 4        | 
| 2934    | 3        | 
| 2935    | 2        | 
| 2968    | 1        | 
| 3111    | 1        | 
| 3174    | 1        | 
| 3286    | 1        | 
| 3372    | 1        | 
| 3423    | 1        | 
| 3464    | 1        | 
| 3478    | 1        | 
| 3490    | 1        | 
| 3566    | 2        | 
| 3689    | 1        | 
| 3805    | 1        | 
| 3836    | 1        | 
| 3849    | 1        | 
| 3887    | 1        | 
| 3968    | 1        | 
| 4001    | 1        | 
| 4099    | 1        | 
| 4174    | 1        | 
| 4291    | 1        | 
| 4382    | 1        | 
| 4723    | 1        | 
| 5185    | 1        | 
| 5199    | 1        | 
| 5468    | 1        | 
| 5510    | 1        | 
| 5563    | 1        | 
| 6874    | 1        | 
| 7029    | 1        | 
| 7421    | 1        | 
| 13457   | 1        |
