### ISSUE TITLE
consumer: add a timeout for big or buggy repositories.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#44]
To avoid really long processing times due bugs or bottlenecks into borges or go-git, we should add a timeout logic into workers to stop and log the specific repository.

**Comment by ajnavarro** [comment]
@smola at the end, do we want to do this? I think we decided to do not add a timeout.

**Comment by smola** [comment]
@ajnavarro Now we can do this with https://github.com/src-d/go-git/issues/483

We just have to decide what kind of cancellation policy do we want and add it.

**Comment by mcarmonaa** [comment]
Timeout added in PR https://github.com/src-d/borges/pull/144

**Comment by ajnavarro** [comment]
Merged.
