### ISSUE TITLE
AMQP best practices recommends one channel per thread

### ISSUE THREAD

**Issue by alcortesm** [src-d/borges#62]
In the current version, the `Consumer` is a single thread reading from an AMQP `Channel` and distributing the jobs among several workers in a `Workerpool`.

The number of workers in the workerpool can be adjusted dynamically, but in doing so, the flow control over the AMQP channel gets outdated, resulting in either too few jobs in-flight or too many, given the new number of workers in the workerpool.

Most best practices articles and the very own AMQP specs hint that the correct way to do this is to actually have a channel per thread (worker), which has the extra benefit that we can start using `Channel.Qos` for its real intended purpose, which is to keep the consumers busy while keeping mosts jobs safe in the broker.

This change will imply a major refactor of consumer, instead of having:

`a single thread consumer fetching from a single channel from the broker and distributing jobs among the several workers in a dynamic workerpool`

we will need to change to:

`a dynamic pool of consumers, each of them with a single associated worker and fetching from their own broker channel; this is, we will have as many consumer and channels as we have workers`

A few links about this topic:

- https://www.rabbitmq.com/api-guide.html#channel-threads
  > As a rule of thumb, sharing Channel instances between threads is something to be avoided. 
- https://www.rabbitmq.com/tutorials/amqp-concepts.html#amqp-channels
  > For applications that use multiple threads/processes for processing, it is very common to open a new channel per thread/process and not share channels between them.
- http://mikehadlow.blogspot.com.es/2013/09/rabbitmq-amqp-channel-best-practices.html
  > Channels are not thread safe. You should create and use a channel on a single thread.
- https://www.rabbitmq.com/consumer-prefetch.html

While none of this quotes address our problem at hand directly and some of them miss the point entirely as we are not accessing the same channel from different threads,  you can get an idea of what was the original purpose and design of channels and their expected usage.

**Comment by erizocosmico** [comment]
Should we close this or are we actually planning on implementing this?

**Comment by smola** [comment]
Given that we are now using borges instances with a single thread, this is probably not relevant anymore.
