### ISSUE TITLE
Add `borges version`

### ISSUE THREAD

**Issue by bzz** [src-d/borges#71]
As a developer responsible to deployment of Borges to k8s cluster,
I would like to be able to tell for sure which version is currently deployed. 

This can be done by executing `borges --version` or some other similar command

**Comment by ajnavarro** [comment]
Actually working: 

`borges - 1.0.0 (build 07-06-2017_12_04_44)`

Steps to reproduce:

- `rm Makefile.main; rm -rf .ci`
- `make dependencies`
- `CI=true TRAVIS_TAG=1.0.0 TRAVIS_BUILD_DIR=~/work/src/github.com/src-d/borges make packages`
- `./build/borges_linux_amd64/borges version`
