### ISSUE TITLE
Consumer: can not process the repository `error="reference not found"`

### ISSUE THREAD

**Issue by bzz** [src-d/borges#72]
Was running locally \w #70 and #69 merged

It seems 
 - https://github.com/CyanogenMod/android_hardware_qcom_fm 
 - https://github.com/poojakarthik/Vericon
 - https://github.com/ev3dev/avahi
 - https://github.com/AOKP/device_motorola_otus
 - https://github.com/Tbsc/Techy
 - https://github.com/QawsQAER/ESDC2014
 - https://github.com/qwio2000/Hongkong
 

all fail with similar error

```
EROR[06-29|19:37:51] job errored                              module=borges WorkerID=1 RepositoryID=015cf4de-12fb-544d-8256-d12250ab8ac4 error="reference not found" caller=consumer.go:49
EROR[06-29|19:37:51] error on job                             module=worker id=1 err="reference not found" caller=worker.go:46
DBUG[06-29|19:37:51] job started                              module=borges WorkerID=1 RepositoryID=015cf4de-12fb-544d-8256-d12250ab8ac4 caller=consumer.go:44
DBUG[06-29|19:37:51] repository model obtained                job=015cf4de-12fb-544d-8256-d12250ab8ac4 status=pending last-fetch=nil references=0 caller=archiver.go:93
DBUG[06-29|19:37:51] endpoint selected                        job=015cf4de-12fb-544d-8256-d12250ab8ac4 endpoint=git://github.com/CyanogenMod/android_hardware_qcom_fm.git caller=archiver.go:100
DBUG[06-29|19:37:51] local temporary directory created        job=015cf4de-12fb-544d-8256-d12250ab8ac4 temp-path=local_repos/015cf4de-12fb-544d-8256-d12250ab8ac4/1498757871629244230 caller=archiver.go:109
DBUG[06-29|19:37:51] local repository created                 job=015cf4de-12fb-544d-8256-d12250ab8ac4 caller=archiver.go:116
DBUG[06-29|19:38:02] changes obtained                         job=015cf4de-12fb-544d-8256-d12250ab8ac4 roots=1 caller=archiver.go:143
```

~For debugging - it would be nice not to get it infinity re-scheduled but rather keep it somewhere for a while (separate queue?).~ _update_ this was moved to #73

**Comment by alcortesm** [comment]
a counter in the job that gets incremented everytime a job is resqueduled?

Then when rescheduling, check the counter and if it is too high send to a "really-dead-don't-reschedule-queue" instead.

**Comment by ajnavarro** [comment]
@alcortesm actually, all failed repos are keept in the dead-letter queue. For something, in this case is not.

**Comment by ajnavarro** [comment]
@alcortesm here is an example about the metadata that is into a failed job:
![buried-example](https://user-images.githubusercontent.com/1196465/27726920-a59a2db6-5d7c-11e7-9b81-5488da9a4d1a.png)

It's also counting the times that was rejected too, but right now we don't have any policy to requeue this failed jobs into the main queue.

**Comment by ajnavarro** [comment]
@bzz This repository doesn't have master branch, the problem could come from this.

**Comment by bzz** [comment]
@ajnavarro True. What is the expected failure mode for such case?

**Comment by ajnavarro** [comment]
@bzz we souldn't fail ;D

**Comment by bzz** [comment]
Found 6 more cases of what seems to be the same error, updated PR description

**Comment by ajnavarro** [comment]
Could be related: https://github.com/src-d/go-git/issues/460

**Comment by bzz** [comment]
On 2000 repos there are 12 more cases of this error.
