### ISSUE TITLE
Consumer: verify performance on 99mb repo

### ISSUE THREAD

**Issue by bzz** [src-d/borges#75]
Processing of 

 - https://github.com/upsilonproject/upsilon-common 
 - https://github.com/hclivess/Bismuth

seems to take _40 min_ each.

It's a 100+mb repo with 500+ commits. 

This issue is about investigating the root cause of this slowdown.

**Comment by erizocosmico** [comment]
I'm taking a look at this

**Comment by erizocosmico** [comment]
Some preliminary analysis:

It takes consistently ~8min to clone the repo (about 1 or 2 with CLI git) in borges and then when it takes forever is pushing to the rooted repos:

```
DBUG[08-09|14:53:40] repository model obtained                module=borges worker=0 job=015dc69e-dd1d-eedc-f9d4-2a5ec3829a1f status=pending last-fetch=nil references=0 caller=archiver.go:90
DBUG[08-09|15:01:13] remote repository cloned                 module=borges worker=0 job=015dc69e-dd1d-eedc-f9d4-2a5ec3829a1f endpoint=https://github.com/hclivess/Bismuth caller=archiver.go:128
DBUG[08-09|15:01:38] changes obtained                         module=borges worker=0 job=015dc69e-dd1d-eedc-f9d4-2a5ec3829a1f endpoint=https://github.com/hclivess/Bismuth roots=1 caller=archiver.go:138
DBUG[08-09|15:01:38] push changes to rooted repository started module=borges worker=0 job=015dc69e-dd1d-eedc-f9d4-2a5ec3829a1f endpoint=https://github.com/hclivess/Bismuth root=54f64e3633ccf9cfcff7f45f1302fca57e0ebfe2 caller=archiver.go:191
```

I did a pprof (or 1min) of borges during the push phase and the top 10 are:

```
      flat  flat%   sum%        cum   cum%
    25.95s 43.39% 43.39%     29.21s 48.84%  runtime.mapaccess2_fast32
     5.97s  9.98% 53.37%      5.97s  9.98%  hash/adler32.update
     5.52s  9.23% 62.60%      5.52s  9.23%  github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.matchLength
     3.82s  6.39% 68.99%      3.82s  6.39%  runtime.aeshash32
     2.68s  4.48% 73.47%      4.69s  7.84%  runtime.mapassign
     2.53s  4.23% 77.70%     43.45s 72.65%  github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.findMatch
     1.55s  2.59% 80.29%      1.92s  3.21%  bytes.(*Buffer).grow
     1.32s  2.21% 82.49%      1.32s  2.21%  runtime.memmove
     1.30s  2.17% 84.67%     54.93s 91.84%  github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.DiffDelta
     1.29s  2.16% 86.82%      7.19s 12.02%  hash/adler32.Checksum
```

So most of the time spent there is in calculating hashes and accessing map (the index created in `initMatch` at `gopkg.in/src-d/go-git.v4/plumbing/format/packfile`)

54.93s of 60s are spent on `DiffDelta` (which is the parent of all those hashes and map accesses). At first sight, that seems to be the bottleneck.

**Comment by erizocosmico** [comment]
Can you try again when [this](https://github.com/src-d/borges/pull/152) is merged? This should hopefully put and end to these problems.

**Comment by bzz** [comment]
@erizocosmico do you think this is still reproducible on latest borges/go-git?

**Comment by erizocosmico** [comment]
We'd have to try, can't tell for sure without trying with these specific repos.

**Comment by jfontan** [comment]
Times have decreased considerably:

* upsilon: 2 minutes
* Bismuth: 12 minutes

The changes will be live in the next borges version.
