### ISSUE TITLE
Consumer: out of 200, 2 messages suck in the queue

### ISSUE THREAD

**Issue by bzz** [src-d/borges#80]
After 24h for processing top 178 repositories (same file as in #78 ), there were 2 that seems stuck(re-schedulled?) in the main queue forever \w CPU% != 0.

Both had payload `gaxSZXBvc2l0b3J5SUTEEAFc+Ucr70NX9CQFPcYv14s=` with is `base64(msgpack)` and quite hard to debug :/ 

According to http://sugendran.github.io/msgpack-visualizer/ and http://kawanet.github.io/msgpack-lite/ it seems to be

```
81 AC 52 65 70 6F 73 69 74 6F 72 79 49 44 82 A4 74 79 70 65 A6 42 75 66 66 65 72 A4 64 61 74 61 DC 00 10 01 5C CC F9 47 2B CC EF 43 57 CC F4 24 05 3D CC C6 2F CC D7 CC 8B
```

or

```
{
  "RepositoryID": {
    "type": "Buffer",
    "data": [
      1,
      92,
      249,
      71,
      43,
      239,
      67,
      87,
      244,
      36,
      5,
      61,
      198,
      47,
      215,
      139
    ]
  }
}
```

**Comment by ajnavarro** [comment]
@bzz this is the ID of this repo: 015cf947-2bef-4357-f424-053dc62fd78b

**Comment by smola** [comment]
@bzz Unless you have access to the database  used for this and can retrieve the repository URL, we should close this.
