### ISSUE TITLE
`make test` creates a `verdor` dir but `make packages` doesn't

### ISSUE THREAD

**Issue by alcortesm** [src-d/borges#83]
As a developer of borges I find confusing that `make packages` does not leave a `vendor` directory in my project but `make test` does.

Maybe we can document why this is happening.

**Comment by ajnavarro** [comment]
This should be an issue in CI repository. Anyways, I improve the build instructions with all the needed steps: https://github.com/src-d/borges/pull/84

**Comment by alcortesm** [comment]
Please note that the ci repo does not define `make test`, it is in borges where `make test` is defined, that's why I opened this here.

**Comment by ajnavarro** [comment]
It was a temporal fix for glide support. Now ci repository supports it. See: https://github.com/src-d/borges/pull/77/files#diff-b67911656ef5d18c4ae36cb6741b7965L40

**Comment by alcortesm** [comment]
Nice.

Do you know if merging https://github.com/src-d/borges/pull/77 will fix the issue explained here (the `vendor` directory being created when running `make test` but not when running `make packages`)?

If you don't know, let's wait until it is merged and I will test it manually.

**Comment by smola** [comment]
@alcortesm No, I don't think it fixes the problem. In fact, it is now required to run `make dependencies` explicit before both of them.

**Comment by smola** [comment]
Note that this kind of issue should be solved now in https://github.com/src-d/ci

**Comment by alcortesm** [comment]
ok, I'm moving this issue there, thanks!
