### ISSUE TITLE
Codecov appears to be broken after make the repository public

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#89]
After make public this repository Codecov appears to not be able to compare coverage using master branch:

![codecov-broken](https://user-images.githubusercontent.com/1196465/27862604-4df4c252-6186-11e7-8465-b1a86b2547fe.png)

Maybe we will need to re-add repository to codecov.

**Comment by alcortesm** [comment]
At least for my forks, it was not enough to make them public to make git work: I had to delete them and create them again by forking again from the upstream repo.

This might be the same problem but with codecov.

**Comment by smola** [comment]
It's trying to compare against a commit in master that failed in Travis, so no coverage was uploaded.
This is expected behavior.
